// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: api/user/service/v1/session.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "om-platform/pkg/utils/pagination/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建会话请求
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                // 用户ID
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                                                           // 客户端IP
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`                                                        // 用户代理
	DeviceInfo    string                 `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`                                                     // 设备信息
	SessionType   string                 `protobuf:"bytes,5,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`                                                  // 会话类型(WEB/MOBILE/API/CLI)
	TenantId      uint32                 `protobuf:"varint,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                          // 租户ID
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	Ttl           uint32                 `protobuf:"varint,8,opt,name=ttl,proto3" json:"ttl,omitempty"`                                                                                    // 生存时间(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSessionRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *CreateSessionRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *CreateSessionRequest) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

func (x *CreateSessionRequest) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *CreateSessionRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CreateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateSessionRequest) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// 创建会话响应
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // 过期时间
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                          // 会话令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateSessionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateSessionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取会话请求
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 会话信息
type SessionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                         // 会话ID
	UserId         uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                 // 用户ID
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                                                                            // 用户名
	ClientIp       string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                                                            // 客户端IP
	UserAgent      string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`                                                         // 用户代理
	DeviceInfo     string                 `protobuf:"bytes,6,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`                                                      // 设备信息
	SessionType    string                 `protobuf:"bytes,7,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`                                                   // 会话类型
	TenantId       uint32                 `protobuf:"varint,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                           // 租户ID
	TenantName     string                 `protobuf:"bytes,9,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`                                                      // 租户名称
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                        // 创建时间
	LastActivityAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`                                       // 最后活动时间
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                                                        // 过期时间
	IsActive       bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                                                          // 是否活跃
	Metadata       map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	Permissions    []string               `protobuf:"bytes,15,rep,name=permissions,proto3" json:"permissions,omitempty"`                                                                     // 权限列表
	Roles          []string               `protobuf:"bytes,16,rep,name=roles,proto3" json:"roles,omitempty"`                                                                                 // 角色列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SessionInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SessionInfo) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SessionInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SessionInfo) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

func (x *SessionInfo) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *SessionInfo) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *SessionInfo) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *SessionInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionInfo) GetLastActivityAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivityAt
	}
	return nil
}

func (x *SessionInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SessionInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SessionInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SessionInfo) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *SessionInfo) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 更新会话请求
type UpdateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                        // 会话ID
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	Ttl           uint32                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`                                                                                    // 生存时间(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateSessionRequest) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// 删除会话请求
type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 查询会话列表请求
type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *v1.PagingRequest      `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`                              // 分页请求
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 用户ID(可选)
	TenantId      uint32                 `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`         // 租户ID(可选)
	SessionType   string                 `protobuf:"bytes,4,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // 会话类型(可选)
	ActiveOnly    bool                   `protobuf:"varint,5,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`   // 仅活跃会话
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`       // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`             // 结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListSessionsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListSessionsRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ListSessionsRequest) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *ListSessionsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListSessionsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListSessionsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// 查询会话列表响应
type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *v1.PagingResponse     `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`     // 分页响应
	Sessions      []*SessionInfo         `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"` // 会话列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *ListSessionsResponse) GetPaging() *v1.PagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// 验证会话有效性请求
type ValidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                          // 会话令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ValidateSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 验证会话有效性响应
type ValidateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`    // 是否有效
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`   // 无效原因
	Session       *SessionInfo           `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"` // 会话信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateSessionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateSessionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ValidateSessionResponse) GetSession() *SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

// 延长会话有效期请求
type ExtendSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Ttl           uint32                 `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`                             // 延长时间(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendSessionRequest) Reset() {
	*x = ExtendSessionRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendSessionRequest) ProtoMessage() {}

func (x *ExtendSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendSessionRequest.ProtoReflect.Descriptor instead.
func (*ExtendSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *ExtendSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExtendSessionRequest) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// 延长会话有效期响应
type ExtendSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=new_expires_at,json=newExpiresAt,proto3" json:"new_expires_at,omitempty"` // 新的过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendSessionResponse) Reset() {
	*x = ExtendSessionResponse{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendSessionResponse) ProtoMessage() {}

func (x *ExtendSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendSessionResponse.ProtoReflect.Descriptor instead.
func (*ExtendSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *ExtendSessionResponse) GetNewExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NewExpiresAt
	}
	return nil
}

// 获取会话统计信息请求
type GetSessionStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint32                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`         // 租户ID(可选)
	SessionType   string                 `protobuf:"bytes,2,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // 会话类型(可选)
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`       // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`             // 结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatsRequest) Reset() {
	*x = GetSessionStatsRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatsRequest) ProtoMessage() {}

func (x *GetSessionStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *GetSessionStatsRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetSessionStatsRequest) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *GetSessionStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetSessionStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// 获取会话统计信息响应
type GetSessionStatsResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	TotalSessions      uint32                   `protobuf:"varint,1,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`                                                                                       // 总会话数
	ActiveSessions     uint32                   `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`                                                                                    // 活跃会话数
	ExpiredSessions    uint32                   `protobuf:"varint,3,opt,name=expired_sessions,json=expiredSessions,proto3" json:"expired_sessions,omitempty"`                                                                                 // 过期会话数
	TerminatedSessions uint32                   `protobuf:"varint,4,opt,name=terminated_sessions,json=terminatedSessions,proto3" json:"terminated_sessions,omitempty"`                                                                        // 终止会话数
	SessionsByType     map[string]uint32        `protobuf:"bytes,5,rep,name=sessions_by_type,json=sessionsByType,proto3" json:"sessions_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`        // 按类型统计
	SessionsByTenant   map[uint32]uint32        `protobuf:"bytes,6,rep,name=sessions_by_tenant,json=sessionsByTenant,proto3" json:"sessions_by_tenant,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 按租户统计
	TimeSeries         []*SessionTimeSeriesData `protobuf:"bytes,7,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`                                                                                                 // 时间序列数据
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSessionStatsResponse) Reset() {
	*x = GetSessionStatsResponse{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatsResponse) ProtoMessage() {}

func (x *GetSessionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *GetSessionStatsResponse) GetTotalSessions() uint32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *GetSessionStatsResponse) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *GetSessionStatsResponse) GetExpiredSessions() uint32 {
	if x != nil {
		return x.ExpiredSessions
	}
	return 0
}

func (x *GetSessionStatsResponse) GetTerminatedSessions() uint32 {
	if x != nil {
		return x.TerminatedSessions
	}
	return 0
}

func (x *GetSessionStatsResponse) GetSessionsByType() map[string]uint32 {
	if x != nil {
		return x.SessionsByType
	}
	return nil
}

func (x *GetSessionStatsResponse) GetSessionsByTenant() map[uint32]uint32 {
	if x != nil {
		return x.SessionsByTenant
	}
	return nil
}

func (x *GetSessionStatsResponse) GetTimeSeries() []*SessionTimeSeriesData {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

// 会话时间序列数据
type SessionTimeSeriesData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                            // 时间戳
	ActiveCount   uint32                 `protobuf:"varint,2,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`    // 活跃数量
	NewCount      uint32                 `protobuf:"varint,3,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`             // 新增数量
	ExpiredCount  uint32                 `protobuf:"varint,4,opt,name=expired_count,json=expiredCount,proto3" json:"expired_count,omitempty"` // 过期数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTimeSeriesData) Reset() {
	*x = SessionTimeSeriesData{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTimeSeriesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTimeSeriesData) ProtoMessage() {}

func (x *SessionTimeSeriesData) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTimeSeriesData.ProtoReflect.Descriptor instead.
func (*SessionTimeSeriesData) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{14}
}

func (x *SessionTimeSeriesData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SessionTimeSeriesData) GetActiveCount() uint32 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

func (x *SessionTimeSeriesData) GetNewCount() uint32 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

func (x *SessionTimeSeriesData) GetExpiredCount() uint32 {
	if x != nil {
		return x.ExpiredCount
	}
	return 0
}

// 强制终止会话请求
type ForceTerminateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                        // 终止原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceTerminateSessionRequest) Reset() {
	*x = ForceTerminateSessionRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceTerminateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceTerminateSessionRequest) ProtoMessage() {}

func (x *ForceTerminateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceTerminateSessionRequest.ProtoReflect.Descriptor instead.
func (*ForceTerminateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{15}
}

func (x *ForceTerminateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ForceTerminateSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 批量终止会话请求
type BatchTerminateSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionIds    []string               `protobuf:"bytes,1,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`    // 会话ID列表
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 用户ID(可选，终止指定用户的所有会话)
	TenantId      uint32                 `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`         // 租户ID(可选，终止指定租户的所有会话)
	SessionType   string                 `protobuf:"bytes,4,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // 会话类型(可选，终止指定类型的所有会话)
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                              // 终止原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTerminateSessionsRequest) Reset() {
	*x = BatchTerminateSessionsRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTerminateSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTerminateSessionsRequest) ProtoMessage() {}

func (x *BatchTerminateSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTerminateSessionsRequest.ProtoReflect.Descriptor instead.
func (*BatchTerminateSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{16}
}

func (x *BatchTerminateSessionsRequest) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *BatchTerminateSessionsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BatchTerminateSessionsRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BatchTerminateSessionsRequest) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *BatchTerminateSessionsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 批量终止会话响应
type BatchTerminateSessionsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TerminatedCount  uint32                 `protobuf:"varint,1,opt,name=terminated_count,json=terminatedCount,proto3" json:"terminated_count,omitempty"`     // 终止数量
	FailedSessionIds []string               `protobuf:"bytes,2,rep,name=failed_session_ids,json=failedSessionIds,proto3" json:"failed_session_ids,omitempty"` // 失败的会话ID列表
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchTerminateSessionsResponse) Reset() {
	*x = BatchTerminateSessionsResponse{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTerminateSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTerminateSessionsResponse) ProtoMessage() {}

func (x *BatchTerminateSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTerminateSessionsResponse.ProtoReflect.Descriptor instead.
func (*BatchTerminateSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{17}
}

func (x *BatchTerminateSessionsResponse) GetTerminatedCount() uint32 {
	if x != nil {
		return x.TerminatedCount
	}
	return 0
}

func (x *BatchTerminateSessionsResponse) GetFailedSessionIds() []string {
	if x != nil {
		return x.FailedSessionIds
	}
	return nil
}

// 获取会话活动日志请求
type GetSessionActivityLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Paging        *v1.PagingRequest      `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`                        // 分页请求
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionActivityLogsRequest) Reset() {
	*x = GetSessionActivityLogsRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionActivityLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionActivityLogsRequest) ProtoMessage() {}

func (x *GetSessionActivityLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionActivityLogsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionActivityLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{18}
}

func (x *GetSessionActivityLogsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionActivityLogsRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *GetSessionActivityLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetSessionActivityLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// 获取会话活动日志响应
type GetSessionActivityLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *v1.PagingResponse     `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"` // 分页响应
	Logs          []*SessionActivityLog  `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`     // 日志列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionActivityLogsResponse) Reset() {
	*x = GetSessionActivityLogsResponse{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionActivityLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionActivityLogsResponse) ProtoMessage() {}

func (x *GetSessionActivityLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionActivityLogsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionActivityLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{19}
}

func (x *GetSessionActivityLogsResponse) GetPaging() *v1.PagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *GetSessionActivityLogsResponse) GetLogs() []*SessionActivityLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

// 会话活动日志
type SessionActivityLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`                      // 日志ID
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // 会话ID
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户ID
	ActivityType  string                 `protobuf:"bytes,4,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"` // 活动类型
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // 资源类型
	ResourceId    string                 `protobuf:"bytes,6,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`       // 资源ID
	ClientIp      string                 `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`             // 客户端IP
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // 时间戳
	Details       *structpb.Struct       `protobuf:"bytes,9,opt,name=details,proto3" json:"details,omitempty"`                               // 详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionActivityLog) Reset() {
	*x = SessionActivityLog{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionActivityLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionActivityLog) ProtoMessage() {}

func (x *SessionActivityLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionActivityLog.ProtoReflect.Descriptor instead.
func (*SessionActivityLog) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{20}
}

func (x *SessionActivityLog) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *SessionActivityLog) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionActivityLog) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SessionActivityLog) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *SessionActivityLog) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *SessionActivityLog) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *SessionActivityLog) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SessionActivityLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SessionActivityLog) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

// 设置会话属性请求
type SetSessionAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                              // 键
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                          // 值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionAttributeRequest) Reset() {
	*x = SetSessionAttributeRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionAttributeRequest) ProtoMessage() {}

func (x *SetSessionAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionAttributeRequest.ProtoReflect.Descriptor instead.
func (*SetSessionAttributeRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{21}
}

func (x *SetSessionAttributeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetSessionAttributeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSessionAttributeRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 获取会话属性请求
type GetSessionAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                              // 键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionAttributeRequest) Reset() {
	*x = GetSessionAttributeRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionAttributeRequest) ProtoMessage() {}

func (x *GetSessionAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetSessionAttributeRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{22}
}

func (x *GetSessionAttributeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionAttributeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 获取会话属性响应
type GetSessionAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // 值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionAttributeResponse) Reset() {
	*x = GetSessionAttributeResponse{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionAttributeResponse) ProtoMessage() {}

func (x *GetSessionAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionAttributeResponse.ProtoReflect.Descriptor instead.
func (*GetSessionAttributeResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{23}
}

func (x *GetSessionAttributeResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 删除会话属性请求
type DeleteSessionAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                              // 键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionAttributeRequest) Reset() {
	*x = DeleteSessionAttributeRequest{}
	mi := &file_api_user_service_v1_session_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionAttributeRequest) ProtoMessage() {}

func (x *DeleteSessionAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_session_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionAttributeRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionAttributeRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_session_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteSessionAttributeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteSessionAttributeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_api_user_service_v1_session_proto protoreflect.FileDescriptor

const file_api_user_service_v1_session_proto_rawDesc = "" +
	"\n" +
	"!api/user/service/v1/session.proto\x12\x13api.user.service.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a(pkg/utils/pagination/v1/pagination.proto\"\xf0\x02\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vdevice_info\x18\x04 \x01(\tR\n" +
	"deviceInfo\x12!\n" +
	"\fsession_type\x18\x05 \x01(\tR\vsessionType\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\rR\btenantId\x12S\n" +
	"\bmetadata\x18\a \x03(\v27.api.user.service.v1.CreateSessionRequest.MetadataEntryR\bmetadata\x12\x10\n" +
	"\x03ttl\x18\b \x01(\rR\x03ttl\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x01\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb9\x05\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vdevice_info\x18\x06 \x01(\tR\n" +
	"deviceInfo\x12!\n" +
	"\fsession_type\x18\a \x01(\tR\vsessionType\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\rR\btenantId\x12\x1f\n" +
	"\vtenant_name\x18\t \x01(\tR\n" +
	"tenantName\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12D\n" +
	"\x10last_activity_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0elastActivityAt\x129\n" +
	"\n" +
	"expires_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\x12J\n" +
	"\bmetadata\x18\x0e \x03(\v2..api.user.service.v1.SessionInfo.MetadataEntryR\bmetadata\x12 \n" +
	"\vpermissions\x18\x0f \x03(\tR\vpermissions\x12\x14\n" +
	"\x05roles\x18\x10 \x03(\tR\x05roles\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x14UpdateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12S\n" +
	"\bmetadata\x18\x02 \x03(\v27.api.user.service.v1.UpdateSessionRequest.MetadataEntryR\bmetadata\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\rR\x03ttl\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc1\x02\n" +
	"\x13ListSessionsRequest\x12>\n" +
	"\x06paging\x18\x01 \x01(\v2&.pkg.utils.pagination.v1.PagingRequestR\x06paging\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\rR\btenantId\x12!\n" +
	"\fsession_type\x18\x04 \x01(\tR\vsessionType\x12\x1f\n" +
	"\vactive_only\x18\x05 \x01(\bR\n" +
	"activeOnly\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x95\x01\n" +
	"\x14ListSessionsResponse\x12?\n" +
	"\x06paging\x18\x01 \x01(\v2'.pkg.utils.pagination.v1.PagingResponseR\x06paging\x12<\n" +
	"\bsessions\x18\x02 \x03(\v2 .api.user.service.v1.SessionInfoR\bsessions\"M\n" +
	"\x16ValidateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x83\x01\n" +
	"\x17ValidateSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12:\n" +
	"\asession\x18\x03 \x01(\v2 .api.user.service.v1.SessionInfoR\asession\"G\n" +
	"\x14ExtendSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\rR\x03ttl\"Y\n" +
	"\x15ExtendSessionResponse\x12@\n" +
	"\x0enew_expires_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fnewExpiresAt\"\xca\x01\n" +
	"\x16GetSessionStatsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\rR\btenantId\x12!\n" +
	"\fsession_type\x18\x02 \x01(\tR\vsessionType\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xf8\x04\n" +
	"\x17GetSessionStatsResponse\x12%\n" +
	"\x0etotal_sessions\x18\x01 \x01(\rR\rtotalSessions\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\rR\x0eactiveSessions\x12)\n" +
	"\x10expired_sessions\x18\x03 \x01(\rR\x0fexpiredSessions\x12/\n" +
	"\x13terminated_sessions\x18\x04 \x01(\rR\x12terminatedSessions\x12j\n" +
	"\x10sessions_by_type\x18\x05 \x03(\v2@.api.user.service.v1.GetSessionStatsResponse.SessionsByTypeEntryR\x0esessionsByType\x12p\n" +
	"\x12sessions_by_tenant\x18\x06 \x03(\v2B.api.user.service.v1.GetSessionStatsResponse.SessionsByTenantEntryR\x10sessionsByTenant\x12K\n" +
	"\vtime_series\x18\a \x03(\v2*.api.user.service.v1.SessionTimeSeriesDataR\n" +
	"timeSeries\x1aA\n" +
	"\x13SessionsByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aC\n" +
	"\x15SessionsByTenantEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x15SessionTimeSeriesData\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\factive_count\x18\x02 \x01(\rR\vactiveCount\x12\x1b\n" +
	"\tnew_count\x18\x03 \x01(\rR\bnewCount\x12#\n" +
	"\rexpired_count\x18\x04 \x01(\rR\fexpiredCount\"U\n" +
	"\x1cForceTerminateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xb1\x01\n" +
	"\x1dBatchTerminateSessionsRequest\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\tR\n" +
	"sessionIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\rR\btenantId\x12!\n" +
	"\fsession_type\x18\x04 \x01(\tR\vsessionType\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"y\n" +
	"\x1eBatchTerminateSessionsResponse\x12)\n" +
	"\x10terminated_count\x18\x01 \x01(\rR\x0fterminatedCount\x12,\n" +
	"\x12failed_session_ids\x18\x02 \x03(\tR\x10failedSessionIds\"\xf0\x01\n" +
	"\x1dGetSessionActivityLogsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\x06paging\x18\x02 \x01(\v2&.pkg.utils.pagination.v1.PagingRequestR\x06paging\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x9e\x01\n" +
	"\x1eGetSessionActivityLogsResponse\x12?\n" +
	"\x06paging\x18\x01 \x01(\v2'.pkg.utils.pagination.v1.PagingResponseR\x06paging\x12;\n" +
	"\x04logs\x18\x02 \x03(\v2'.api.user.service.v1.SessionActivityLogR\x04logs\"\xd8\x02\n" +
	"\x12SessionActivityLog\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12#\n" +
	"\ractivity_type\x18\x04 \x01(\tR\factivityType\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x06 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\tR\bclientIp\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x121\n" +
	"\adetails\x18\t \x01(\v2\x17.google.protobuf.StructR\adetails\"c\n" +
	"\x1aSetSessionAttributeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"M\n" +
	"\x1aGetSessionAttributeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"3\n" +
	"\x1bGetSessionAttributeResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"P\n" +
	"\x1dDeleteSessionAttributeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key2\xe9\v\n" +
	"\x0eSessionService\x12h\n" +
	"\rCreateSession\x12).api.user.service.v1.CreateSessionRequest\x1a*.api.user.service.v1.CreateSessionResponse\"\x00\x12X\n" +
	"\n" +
	"GetSession\x12&.api.user.service.v1.GetSessionRequest\x1a .api.user.service.v1.SessionInfo\"\x00\x12T\n" +
	"\rUpdateSession\x12).api.user.service.v1.UpdateSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\rDeleteSession\x12).api.user.service.v1.DeleteSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12e\n" +
	"\fListSessions\x12(.api.user.service.v1.ListSessionsRequest\x1a).api.user.service.v1.ListSessionsResponse\"\x00\x12n\n" +
	"\x0fValidateSession\x12+.api.user.service.v1.ValidateSessionRequest\x1a,.api.user.service.v1.ValidateSessionResponse\"\x00\x12h\n" +
	"\rExtendSession\x12).api.user.service.v1.ExtendSessionRequest\x1a*.api.user.service.v1.ExtendSessionResponse\"\x00\x12n\n" +
	"\x0fGetSessionStats\x12+.api.user.service.v1.GetSessionStatsRequest\x1a,.api.user.service.v1.GetSessionStatsResponse\"\x00\x12d\n" +
	"\x15ForceTerminateSession\x121.api.user.service.v1.ForceTerminateSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x83\x01\n" +
	"\x16BatchTerminateSessions\x122.api.user.service.v1.BatchTerminateSessionsRequest\x1a3.api.user.service.v1.BatchTerminateSessionsResponse\"\x00\x12\x83\x01\n" +
	"\x16GetSessionActivityLogs\x122.api.user.service.v1.GetSessionActivityLogsRequest\x1a3.api.user.service.v1.GetSessionActivityLogsResponse\"\x00\x12`\n" +
	"\x13SetSessionAttribute\x12/.api.user.service.v1.SetSessionAttributeRequest\x1a\x16.google.protobuf.Empty\"\x00\x12z\n" +
	"\x13GetSessionAttribute\x12/.api.user.service.v1.GetSessionAttributeRequest\x1a0.api.user.service.v1.GetSessionAttributeResponse\"\x00\x12f\n" +
	"\x16DeleteSessionAttribute\x122.api.user.service.v1.DeleteSessionAttributeRequest\x1a\x16.google.protobuf.Empty\"\x00B;\n" +
	"\x13api.user.service.v1P\x01Z\"om-platform/api/user/service/v1;v1b\x06proto3"

var (
	file_api_user_service_v1_session_proto_rawDescOnce sync.Once
	file_api_user_service_v1_session_proto_rawDescData []byte
)

func file_api_user_service_v1_session_proto_rawDescGZIP() []byte {
	file_api_user_service_v1_session_proto_rawDescOnce.Do(func() {
		file_api_user_service_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_service_v1_session_proto_rawDesc), len(file_api_user_service_v1_session_proto_rawDesc)))
	})
	return file_api_user_service_v1_session_proto_rawDescData
}

var file_api_user_service_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_user_service_v1_session_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),           // 0: api.user.service.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),          // 1: api.user.service.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),              // 2: api.user.service.v1.GetSessionRequest
	(*SessionInfo)(nil),                    // 3: api.user.service.v1.SessionInfo
	(*UpdateSessionRequest)(nil),           // 4: api.user.service.v1.UpdateSessionRequest
	(*DeleteSessionRequest)(nil),           // 5: api.user.service.v1.DeleteSessionRequest
	(*ListSessionsRequest)(nil),            // 6: api.user.service.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),           // 7: api.user.service.v1.ListSessionsResponse
	(*ValidateSessionRequest)(nil),         // 8: api.user.service.v1.ValidateSessionRequest
	(*ValidateSessionResponse)(nil),        // 9: api.user.service.v1.ValidateSessionResponse
	(*ExtendSessionRequest)(nil),           // 10: api.user.service.v1.ExtendSessionRequest
	(*ExtendSessionResponse)(nil),          // 11: api.user.service.v1.ExtendSessionResponse
	(*GetSessionStatsRequest)(nil),         // 12: api.user.service.v1.GetSessionStatsRequest
	(*GetSessionStatsResponse)(nil),        // 13: api.user.service.v1.GetSessionStatsResponse
	(*SessionTimeSeriesData)(nil),          // 14: api.user.service.v1.SessionTimeSeriesData
	(*ForceTerminateSessionRequest)(nil),   // 15: api.user.service.v1.ForceTerminateSessionRequest
	(*BatchTerminateSessionsRequest)(nil),  // 16: api.user.service.v1.BatchTerminateSessionsRequest
	(*BatchTerminateSessionsResponse)(nil), // 17: api.user.service.v1.BatchTerminateSessionsResponse
	(*GetSessionActivityLogsRequest)(nil),  // 18: api.user.service.v1.GetSessionActivityLogsRequest
	(*GetSessionActivityLogsResponse)(nil), // 19: api.user.service.v1.GetSessionActivityLogsResponse
	(*SessionActivityLog)(nil),             // 20: api.user.service.v1.SessionActivityLog
	(*SetSessionAttributeRequest)(nil),     // 21: api.user.service.v1.SetSessionAttributeRequest
	(*GetSessionAttributeRequest)(nil),     // 22: api.user.service.v1.GetSessionAttributeRequest
	(*GetSessionAttributeResponse)(nil),    // 23: api.user.service.v1.GetSessionAttributeResponse
	(*DeleteSessionAttributeRequest)(nil),  // 24: api.user.service.v1.DeleteSessionAttributeRequest
	nil,                                    // 25: api.user.service.v1.CreateSessionRequest.MetadataEntry
	nil,                                    // 26: api.user.service.v1.SessionInfo.MetadataEntry
	nil,                                    // 27: api.user.service.v1.UpdateSessionRequest.MetadataEntry
	nil,                                    // 28: api.user.service.v1.GetSessionStatsResponse.SessionsByTypeEntry
	nil,                                    // 29: api.user.service.v1.GetSessionStatsResponse.SessionsByTenantEntry
	(*timestamppb.Timestamp)(nil),          // 30: google.protobuf.Timestamp
	(*v1.PagingRequest)(nil),               // 31: pkg.utils.pagination.v1.PagingRequest
	(*v1.PagingResponse)(nil),              // 32: pkg.utils.pagination.v1.PagingResponse
	(*structpb.Struct)(nil),                // 33: google.protobuf.Struct
	(*emptypb.Empty)(nil),                  // 34: google.protobuf.Empty
}
var file_api_user_service_v1_session_proto_depIdxs = []int32{
	25, // 0: api.user.service.v1.CreateSessionRequest.metadata:type_name -> api.user.service.v1.CreateSessionRequest.MetadataEntry
	30, // 1: api.user.service.v1.CreateSessionResponse.created_at:type_name -> google.protobuf.Timestamp
	30, // 2: api.user.service.v1.CreateSessionResponse.expires_at:type_name -> google.protobuf.Timestamp
	30, // 3: api.user.service.v1.SessionInfo.created_at:type_name -> google.protobuf.Timestamp
	30, // 4: api.user.service.v1.SessionInfo.last_activity_at:type_name -> google.protobuf.Timestamp
	30, // 5: api.user.service.v1.SessionInfo.expires_at:type_name -> google.protobuf.Timestamp
	26, // 6: api.user.service.v1.SessionInfo.metadata:type_name -> api.user.service.v1.SessionInfo.MetadataEntry
	27, // 7: api.user.service.v1.UpdateSessionRequest.metadata:type_name -> api.user.service.v1.UpdateSessionRequest.MetadataEntry
	31, // 8: api.user.service.v1.ListSessionsRequest.paging:type_name -> pkg.utils.pagination.v1.PagingRequest
	30, // 9: api.user.service.v1.ListSessionsRequest.start_time:type_name -> google.protobuf.Timestamp
	30, // 10: api.user.service.v1.ListSessionsRequest.end_time:type_name -> google.protobuf.Timestamp
	32, // 11: api.user.service.v1.ListSessionsResponse.paging:type_name -> pkg.utils.pagination.v1.PagingResponse
	3,  // 12: api.user.service.v1.ListSessionsResponse.sessions:type_name -> api.user.service.v1.SessionInfo
	3,  // 13: api.user.service.v1.ValidateSessionResponse.session:type_name -> api.user.service.v1.SessionInfo
	30, // 14: api.user.service.v1.ExtendSessionResponse.new_expires_at:type_name -> google.protobuf.Timestamp
	30, // 15: api.user.service.v1.GetSessionStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	30, // 16: api.user.service.v1.GetSessionStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	28, // 17: api.user.service.v1.GetSessionStatsResponse.sessions_by_type:type_name -> api.user.service.v1.GetSessionStatsResponse.SessionsByTypeEntry
	29, // 18: api.user.service.v1.GetSessionStatsResponse.sessions_by_tenant:type_name -> api.user.service.v1.GetSessionStatsResponse.SessionsByTenantEntry
	14, // 19: api.user.service.v1.GetSessionStatsResponse.time_series:type_name -> api.user.service.v1.SessionTimeSeriesData
	30, // 20: api.user.service.v1.SessionTimeSeriesData.timestamp:type_name -> google.protobuf.Timestamp
	31, // 21: api.user.service.v1.GetSessionActivityLogsRequest.paging:type_name -> pkg.utils.pagination.v1.PagingRequest
	30, // 22: api.user.service.v1.GetSessionActivityLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	30, // 23: api.user.service.v1.GetSessionActivityLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	32, // 24: api.user.service.v1.GetSessionActivityLogsResponse.paging:type_name -> pkg.utils.pagination.v1.PagingResponse
	20, // 25: api.user.service.v1.GetSessionActivityLogsResponse.logs:type_name -> api.user.service.v1.SessionActivityLog
	30, // 26: api.user.service.v1.SessionActivityLog.timestamp:type_name -> google.protobuf.Timestamp
	33, // 27: api.user.service.v1.SessionActivityLog.details:type_name -> google.protobuf.Struct
	0,  // 28: api.user.service.v1.SessionService.CreateSession:input_type -> api.user.service.v1.CreateSessionRequest
	2,  // 29: api.user.service.v1.SessionService.GetSession:input_type -> api.user.service.v1.GetSessionRequest
	4,  // 30: api.user.service.v1.SessionService.UpdateSession:input_type -> api.user.service.v1.UpdateSessionRequest
	5,  // 31: api.user.service.v1.SessionService.DeleteSession:input_type -> api.user.service.v1.DeleteSessionRequest
	6,  // 32: api.user.service.v1.SessionService.ListSessions:input_type -> api.user.service.v1.ListSessionsRequest
	8,  // 33: api.user.service.v1.SessionService.ValidateSession:input_type -> api.user.service.v1.ValidateSessionRequest
	10, // 34: api.user.service.v1.SessionService.ExtendSession:input_type -> api.user.service.v1.ExtendSessionRequest
	12, // 35: api.user.service.v1.SessionService.GetSessionStats:input_type -> api.user.service.v1.GetSessionStatsRequest
	15, // 36: api.user.service.v1.SessionService.ForceTerminateSession:input_type -> api.user.service.v1.ForceTerminateSessionRequest
	16, // 37: api.user.service.v1.SessionService.BatchTerminateSessions:input_type -> api.user.service.v1.BatchTerminateSessionsRequest
	18, // 38: api.user.service.v1.SessionService.GetSessionActivityLogs:input_type -> api.user.service.v1.GetSessionActivityLogsRequest
	21, // 39: api.user.service.v1.SessionService.SetSessionAttribute:input_type -> api.user.service.v1.SetSessionAttributeRequest
	22, // 40: api.user.service.v1.SessionService.GetSessionAttribute:input_type -> api.user.service.v1.GetSessionAttributeRequest
	24, // 41: api.user.service.v1.SessionService.DeleteSessionAttribute:input_type -> api.user.service.v1.DeleteSessionAttributeRequest
	1,  // 42: api.user.service.v1.SessionService.CreateSession:output_type -> api.user.service.v1.CreateSessionResponse
	3,  // 43: api.user.service.v1.SessionService.GetSession:output_type -> api.user.service.v1.SessionInfo
	34, // 44: api.user.service.v1.SessionService.UpdateSession:output_type -> google.protobuf.Empty
	34, // 45: api.user.service.v1.SessionService.DeleteSession:output_type -> google.protobuf.Empty
	7,  // 46: api.user.service.v1.SessionService.ListSessions:output_type -> api.user.service.v1.ListSessionsResponse
	9,  // 47: api.user.service.v1.SessionService.ValidateSession:output_type -> api.user.service.v1.ValidateSessionResponse
	11, // 48: api.user.service.v1.SessionService.ExtendSession:output_type -> api.user.service.v1.ExtendSessionResponse
	13, // 49: api.user.service.v1.SessionService.GetSessionStats:output_type -> api.user.service.v1.GetSessionStatsResponse
	34, // 50: api.user.service.v1.SessionService.ForceTerminateSession:output_type -> google.protobuf.Empty
	17, // 51: api.user.service.v1.SessionService.BatchTerminateSessions:output_type -> api.user.service.v1.BatchTerminateSessionsResponse
	19, // 52: api.user.service.v1.SessionService.GetSessionActivityLogs:output_type -> api.user.service.v1.GetSessionActivityLogsResponse
	34, // 53: api.user.service.v1.SessionService.SetSessionAttribute:output_type -> google.protobuf.Empty
	23, // 54: api.user.service.v1.SessionService.GetSessionAttribute:output_type -> api.user.service.v1.GetSessionAttributeResponse
	34, // 55: api.user.service.v1.SessionService.DeleteSessionAttribute:output_type -> google.protobuf.Empty
	42, // [42:56] is the sub-list for method output_type
	28, // [28:42] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_api_user_service_v1_session_proto_init() }
func file_api_user_service_v1_session_proto_init() {
	if File_api_user_service_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_service_v1_session_proto_rawDesc), len(file_api_user_service_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_service_v1_session_proto_goTypes,
		DependencyIndexes: file_api_user_service_v1_session_proto_depIdxs,
		MessageInfos:      file_api_user_service_v1_session_proto_msgTypes,
	}.Build()
	File_api_user_service_v1_session_proto = out.File
	file_api_user_service_v1_session_proto_goTypes = nil
	file_api_user_service_v1_session_proto_depIdxs = nil
}
