// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: api/user/service/v1/tenant.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "om-platform/pkg/utils/pagination/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 租户
type Tenant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *uint32                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                                      // 租户ID
	Name           *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`                                   // 租户名称
	Code           *string                `protobuf:"bytes,3,opt,name=code,proto3,oneof" json:"code,omitempty"`                                   // 租户编码
	MemberCount    *int32                 `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3,oneof" json:"member_count,omitempty"` // 成员数量
	ParentId       *uint32                `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`          // 父租户ID
	Level          *int32                 `protobuf:"varint,6,opt,name=level,proto3,oneof" json:"level,omitempty"`                                // 租户层级
	Path           *string                `protobuf:"bytes,7,opt,name=path,proto3,oneof" json:"path,omitempty"`                                   // 租户路径，格式：1,2,3
	Status         *string                `protobuf:"bytes,8,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Remark         *string                `protobuf:"bytes,9,opt,name=remark,proto3,oneof" json:"remark,omitempty"`                       // 备注
	CreateBy       *uint32                `protobuf:"varint,10,opt,name=create_by,json=createBy,proto3,oneof" json:"create_by,omitempty"` // 创建者ID
	UpdateBy       *uint32                `protobuf:"varint,11,opt,name=update_by,json=updateBy,proto3,oneof" json:"update_by,omitempty"` // 更新者ID
	SubscriptionAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=subscription_at,json=subscriptionAt,proto3,oneof" json:"subscription_at,omitempty"`
	UnsubscribeAt  *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=unsubscribe_at,json=unsubscribeAt,proto3,oneof" json:"unsubscribe_at,omitempty"`
	CreateTime     *timestamppb.Timestamp `protobuf:"bytes,200,opt,name=create_time,json=createTime,proto3,oneof" json:"create_time,omitempty"` // 创建时间
	UpdateTime     *timestamppb.Timestamp `protobuf:"bytes,201,opt,name=update_time,json=updateTime,proto3,oneof" json:"update_time,omitempty"` // 更新时间
	DeleteTime     *timestamppb.Timestamp `protobuf:"bytes,202,opt,name=delete_time,json=deleteTime,proto3,oneof" json:"delete_time,omitempty"` // 删除时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Tenant) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Tenant) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *Tenant) GetMemberCount() int32 {
	if x != nil && x.MemberCount != nil {
		return *x.MemberCount
	}
	return 0
}

func (x *Tenant) GetParentId() uint32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *Tenant) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *Tenant) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *Tenant) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *Tenant) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *Tenant) GetCreateBy() uint32 {
	if x != nil && x.CreateBy != nil {
		return *x.CreateBy
	}
	return 0
}

func (x *Tenant) GetUpdateBy() uint32 {
	if x != nil && x.UpdateBy != nil {
		return *x.UpdateBy
	}
	return 0
}

func (x *Tenant) GetSubscriptionAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubscriptionAt
	}
	return nil
}

func (x *Tenant) GetUnsubscribeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UnsubscribeAt
	}
	return nil
}

func (x *Tenant) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Tenant) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Tenant) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

// 租户列表 - 答复
type ListTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Tenant              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantResponse) Reset() {
	*x = ListTenantResponse{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantResponse) ProtoMessage() {}

func (x *ListTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantResponse.ProtoReflect.Descriptor instead.
func (*ListTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *ListTenantResponse) GetItems() []*Tenant {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListTenantResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 租户数据 - 请求
type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenantRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 创建租户 - 请求
type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Tenant                `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	OperatorId    *uint32                `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"` // 操作用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTenantRequest) GetData() *Tenant {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateTenantRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

// 更新租户 -请求
type UpdateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    *uint32                `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"` // 操作用户ID
	Data          *Tenant                `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`              // 要更新的字段列表
	AllowMissing  *bool                  `protobuf:"varint,4,opt,name=allow_missing,json=allowMissing,proto3,oneof" json:"allow_missing,omitempty"` // 如果设置为true的时候，资源不存在则会新增(插入)，并且在这种情况下`updateMask`字段将会被忽略。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTenantRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

func (x *UpdateTenantRequest) GetData() *Tenant {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateTenantRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateTenantRequest) GetAllowMissing() bool {
	if x != nil && x.AllowMissing != nil {
		return *x.AllowMissing
	}
	return false
}

// 删除租户 - 请求
type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId    *uint32                `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"` // 操作用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTenantRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteTenantRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

// 查询子租户列表 - 请求
type ListSubTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      uint32                 `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Paging        *v1.PagingRequest      `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubTenantRequest) Reset() {
	*x = ListSubTenantRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubTenantRequest) ProtoMessage() {}

func (x *ListSubTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubTenantRequest.ProtoReflect.Descriptor instead.
func (*ListSubTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *ListSubTenantRequest) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ListSubTenantRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

// 创建子租户 - 请求
type CreateSubTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      uint32                 `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Data          *Tenant                `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	OperatorId    *uint32                `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"` // 操作用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubTenantRequest) Reset() {
	*x = CreateSubTenantRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubTenantRequest) ProtoMessage() {}

func (x *CreateSubTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateSubTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSubTenantRequest) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateSubTenantRequest) GetData() *Tenant {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateSubTenantRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

// 租户资源配额
type TenantQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	TenantId      *uint32                `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	MaxUsers      *int32                 `protobuf:"varint,3,opt,name=max_users,json=maxUsers,proto3,oneof" json:"max_users,omitempty"`
	MaxGroups     *int32                 `protobuf:"varint,4,opt,name=max_groups,json=maxGroups,proto3,oneof" json:"max_groups,omitempty"`
	MaxProjects   *int32                 `protobuf:"varint,5,opt,name=max_projects,json=maxProjects,proto3,oneof" json:"max_projects,omitempty"`
	MaxStorageGb  *int32                 `protobuf:"varint,6,opt,name=max_storage_gb,json=maxStorageGb,proto3,oneof" json:"max_storage_gb,omitempty"`
	MaxSubTenants *int32                 `protobuf:"varint,7,opt,name=max_sub_tenants,json=maxSubTenants,proto3,oneof" json:"max_sub_tenants,omitempty"`
	CreateBy      *uint32                `protobuf:"varint,8,opt,name=create_by,json=createBy,proto3,oneof" json:"create_by,omitempty"`
	UpdateBy      *uint32                `protobuf:"varint,9,opt,name=update_by,json=updateBy,proto3,oneof" json:"update_by,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,200,opt,name=create_time,json=createTime,proto3,oneof" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,201,opt,name=update_time,json=updateTime,proto3,oneof" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantQuota) Reset() {
	*x = TenantQuota{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantQuota) ProtoMessage() {}

func (x *TenantQuota) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantQuota.ProtoReflect.Descriptor instead.
func (*TenantQuota) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *TenantQuota) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TenantQuota) GetTenantId() uint32 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *TenantQuota) GetMaxUsers() int32 {
	if x != nil && x.MaxUsers != nil {
		return *x.MaxUsers
	}
	return 0
}

func (x *TenantQuota) GetMaxGroups() int32 {
	if x != nil && x.MaxGroups != nil {
		return *x.MaxGroups
	}
	return 0
}

func (x *TenantQuota) GetMaxProjects() int32 {
	if x != nil && x.MaxProjects != nil {
		return *x.MaxProjects
	}
	return 0
}

func (x *TenantQuota) GetMaxStorageGb() int32 {
	if x != nil && x.MaxStorageGb != nil {
		return *x.MaxStorageGb
	}
	return 0
}

func (x *TenantQuota) GetMaxSubTenants() int32 {
	if x != nil && x.MaxSubTenants != nil {
		return *x.MaxSubTenants
	}
	return 0
}

func (x *TenantQuota) GetCreateBy() uint32 {
	if x != nil && x.CreateBy != nil {
		return *x.CreateBy
	}
	return 0
}

func (x *TenantQuota) GetUpdateBy() uint32 {
	if x != nil && x.UpdateBy != nil {
		return *x.UpdateBy
	}
	return 0
}

func (x *TenantQuota) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *TenantQuota) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// 查询租户资源配额 - 请求
type GetTenantQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint32                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantQuotaRequest) Reset() {
	*x = GetTenantQuotaRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantQuotaRequest) ProtoMessage() {}

func (x *GetTenantQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetTenantQuotaRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *GetTenantQuotaRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

// 更新租户资源配额 - 请求
type UpdateTenantQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TenantQuota           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	OperatorId    *uint32                `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"` // 操作用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantQuotaRequest) Reset() {
	*x = UpdateTenantQuotaRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantQuotaRequest) ProtoMessage() {}

func (x *UpdateTenantQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantQuotaRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantQuotaRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTenantQuotaRequest) GetData() *TenantQuota {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateTenantQuotaRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateTenantQuotaRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

// 获取租户权限列表 - 请求
type GetTenantPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint32                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantPermissionsRequest) Reset() {
	*x = GetTenantPermissionsRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantPermissionsRequest) ProtoMessage() {}

func (x *GetTenantPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetTenantPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *GetTenantPermissionsRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

// 获取租户权限列表 - 响应
type GetTenantPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantPermissionsResponse) Reset() {
	*x = GetTenantPermissionsResponse{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantPermissionsResponse) ProtoMessage() {}

func (x *GetTenantPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetTenantPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *GetTenantPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// 批量分配租户权限 - 请求
type BatchAssignTenantPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    *uint32                `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`           // 操作用户ID
	TenantId      uint32                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                       // 租户ID
	PermissionIds []uint32               `protobuf:"varint,3,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"` // 权限ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAssignTenantPermissionRequest) Reset() {
	*x = BatchAssignTenantPermissionRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAssignTenantPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAssignTenantPermissionRequest) ProtoMessage() {}

func (x *BatchAssignTenantPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAssignTenantPermissionRequest.ProtoReflect.Descriptor instead.
func (*BatchAssignTenantPermissionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *BatchAssignTenantPermissionRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

func (x *BatchAssignTenantPermissionRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BatchAssignTenantPermissionRequest) GetPermissionIds() []uint32 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

// 批量撤销租户权限 - 请求
type BatchRevokeTenantPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    *uint32                `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`           // 操作用户ID
	TenantId      uint32                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                       // 租户ID
	PermissionIds []uint32               `protobuf:"varint,3,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"` // 权限ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRevokeTenantPermissionRequest) Reset() {
	*x = BatchRevokeTenantPermissionRequest{}
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRevokeTenantPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRevokeTenantPermissionRequest) ProtoMessage() {}

func (x *BatchRevokeTenantPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRevokeTenantPermissionRequest.ProtoReflect.Descriptor instead.
func (*BatchRevokeTenantPermissionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *BatchRevokeTenantPermissionRequest) GetOperatorId() uint32 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

func (x *BatchRevokeTenantPermissionRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BatchRevokeTenantPermissionRequest) GetPermissionIds() []uint32 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

var File_api_user_service_v1_tenant_proto protoreflect.FileDescriptor

const file_api_user_service_v1_tenant_proto_rawDesc = "" +
	"\n" +
	" api/user/service/v1/tenant.proto\x12\x13api.user.service.v1\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a(pkg/utils/pagination/v1/pagination.proto\x1a$api/user/service/v1/permission.proto\"\xce\t\n" +
	"\x06Tenant\x12#\n" +
	"\x02id\x18\x01 \x01(\rB\x0e\xbaG\v\x92\x02\b租户IDH\x00R\x02id\x88\x01\x01\x12+\n" +
	"\x04name\x18\x02 \x01(\tB\x12\xbaG\x0f\x92\x02\f租户名称H\x01R\x04name\x88\x01\x01\x12+\n" +
	"\x04code\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f租户编码H\x02R\x04code\x88\x01\x01\x12:\n" +
	"\fmember_count\x18\x04 \x01(\x05B\x12\xbaG\x0f\x92\x02\f成员数量H\x03R\vmemberCount\x88\x01\x01\x123\n" +
	"\tparent_id\x18\x05 \x01(\rB\x11\xbaG\x0e\x92\x02\v父租户IDH\x04R\bparentId\x88\x01\x01\x12-\n" +
	"\x05level\x18\x06 \x01(\x05B\x12\xbaG\x0f\x92\x02\f租户层级H\x05R\x05level\x88\x01\x01\x12<\n" +
	"\x04path\x18\a \x01(\tB#\xbaG \x92\x02\x1d租户路径，格式：1,2,3H\x06R\x04path\x88\x01\x01\x12?\n" +
	"\x06status\x18\b \x01(\tB\"\xbaG\x1f\xc2\x01\x04\x12\x02ON\xc2\x01\x05\x12\x03OFF\x8a\x02\x04\x1a\x02ON\x92\x02\x06状态H\aR\x06status\x88\x01\x01\x12)\n" +
	"\x06remark\x18\t \x01(\tB\f\xbaG\t\x92\x02\x06备注H\bR\x06remark\x88\x01\x01\x123\n" +
	"\tcreate_by\x18\n" +
	" \x01(\rB\x11\xbaG\x0e\x92\x02\v创建者IDH\tR\bcreateBy\x88\x01\x01\x123\n" +
	"\tupdate_by\x18\v \x01(\rB\x11\xbaG\x0e\x92\x02\v更新者IDH\n" +
	"R\bupdateBy\x88\x01\x01\x12\\\n" +
	"\x0fsubscription_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x12\xbaG\x0f\x92\x02\f订阅时间H\vR\x0esubscriptionAt\x88\x01\x01\x12Z\n" +
	"\x0eunsubscribe_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\x12\xbaG\x0f\x92\x02\f退订时间H\fR\runsubscribeAt\x88\x01\x01\x12U\n" +
	"\vcreate_time\x18\xc8\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x12\xbaG\x0f\x92\x02\f创建时间H\rR\n" +
	"createTime\x88\x01\x01\x12U\n" +
	"\vupdate_time\x18\xc9\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x12\xbaG\x0f\x92\x02\f更新时间H\x0eR\n" +
	"updateTime\x88\x01\x01\x12U\n" +
	"\vdelete_time\x18\xca\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x12\xbaG\x0f\x92\x02\f删除时间H\x0fR\n" +
	"deleteTime\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_codeB\x0f\n" +
	"\r_member_countB\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_levelB\a\n" +
	"\x05_pathB\t\n" +
	"\a_statusB\t\n" +
	"\a_remarkB\f\n" +
	"\n" +
	"_create_byB\f\n" +
	"\n" +
	"_update_byB\x12\n" +
	"\x10_subscription_atB\x11\n" +
	"\x0f_unsubscribe_atB\x0e\n" +
	"\f_create_timeB\x0e\n" +
	"\f_update_timeB\x0e\n" +
	"\f_delete_time\"]\n" +
	"\x12ListTenantResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.api.user.service.v1.TenantR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\"\n" +
	"\x10GetTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x94\x01\n" +
	"\x13CreateTenantRequest\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.api.user.service.v1.TenantR\x04data\x12<\n" +
	"\voperator_id\x18\x02 \x01(\rB\x16\xbaG\x13\x18\x01\x92\x02\x0e操作用户IDH\x00R\n" +
	"operatorId\x88\x01\x01B\x0e\n" +
	"\f_operator_id\"\xd2\x03\n" +
	"\x13UpdateTenantRequest\x12<\n" +
	"\voperator_id\x18\x01 \x01(\rB\x16\xbaG\x13\x18\x01\x92\x02\x0e操作用户IDH\x00R\n" +
	"operatorId\x88\x01\x01\x12/\n" +
	"\x04data\x18\x02 \x01(\v2\x1b.api.user.service.v1.TenantR\x04data\x12s\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskB6\xbaG3:\x16\x12\x14id,realName,userName\x92\x02\x18要更新的字段列表R\n" +
	"updateMask\x12\xb4\x01\n" +
	"\rallow_missing\x18\x04 \x01(\bB\x89\x01\xbaG\x85\x01\x92\x02\x81\x01如果设置为true的时候，资源不存在则会新增(插入)，并且在这种情况下`updateMask`字段将会被忽略。H\x01R\fallowMissing\x88\x01\x01B\x0e\n" +
	"\f_operator_idB\x10\n" +
	"\x0e_allow_missing\"s\n" +
	"\x13DeleteTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12<\n" +
	"\voperator_id\x18\x02 \x01(\rB\x16\xbaG\x13\x18\x01\x92\x02\x0e操作用户IDH\x00R\n" +
	"operatorId\x88\x01\x01B\x0e\n" +
	"\f_operator_id\"s\n" +
	"\x14ListSubTenantRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\rR\bparentId\x12>\n" +
	"\x06paging\x18\x02 \x01(\v2&.pkg.utils.pagination.v1.PagingRequestR\x06paging\"\xb4\x01\n" +
	"\x16CreateSubTenantRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\rR\bparentId\x12/\n" +
	"\x04data\x18\x02 \x01(\v2\x1b.api.user.service.v1.TenantR\x04data\x12<\n" +
	"\voperator_id\x18\x03 \x01(\rB\x16\xbaG\x13\x18\x01\x92\x02\x0e操作用户IDH\x00R\n" +
	"operatorId\x88\x01\x01B\x0e\n" +
	"\f_operator_id\"\xe8\x06\n" +
	"\vTenantQuota\x12#\n" +
	"\x02id\x18\x01 \x01(\rB\x0e\xbaG\v\x92\x02\b配额IDH\x00R\x02id\x88\x01\x01\x120\n" +
	"\ttenant_id\x18\x02 \x01(\rB\x0e\xbaG\v\x92\x02\b租户IDH\x01R\btenantId\x88\x01\x01\x127\n" +
	"\tmax_users\x18\x03 \x01(\x05B\x15\xbaG\x12\x92\x02\x0f最大用户数H\x02R\bmaxUsers\x88\x01\x01\x12<\n" +
	"\n" +
	"max_groups\x18\x04 \x01(\x05B\x18\xbaG\x15\x92\x02\x12最大用户组数H\x03R\tmaxGroups\x88\x01\x01\x12=\n" +
	"\fmax_projects\x18\x05 \x01(\x05B\x15\xbaG\x12\x92\x02\x0f最大项目数H\x04R\vmaxProjects\x88\x01\x01\x12G\n" +
	"\x0emax_storage_gb\x18\x06 \x01(\x05B\x1c\xbaG\x19\x92\x02\x16最大存储空间(GB)H\x05R\fmaxStorageGb\x88\x01\x01\x12E\n" +
	"\x0fmax_sub_tenants\x18\a \x01(\x05B\x18\xbaG\x15\x92\x02\x12最大子租户数H\x06R\rmaxSubTenants\x88\x01\x01\x123\n" +
	"\tcreate_by\x18\b \x01(\rB\x11\xbaG\x0e\x92\x02\v创建者IDH\aR\bcreateBy\x88\x01\x01\x123\n" +
	"\tupdate_by\x18\t \x01(\rB\x11\xbaG\x0e\x92\x02\v更新者IDH\bR\bupdateBy\x88\x01\x01\x12U\n" +
	"\vcreate_time\x18\xc8\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x12\xbaG\x0f\x92\x02\f创建时间H\tR\n" +
	"createTime\x88\x01\x01\x12U\n" +
	"\vupdate_time\x18\xc9\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x12\xbaG\x0f\x92\x02\f更新时间H\n" +
	"R\n" +
	"updateTime\x88\x01\x01B\x05\n" +
	"\x03_idB\f\n" +
	"\n" +
	"_tenant_idB\f\n" +
	"\n" +
	"_max_usersB\r\n" +
	"\v_max_groupsB\x0f\n" +
	"\r_max_projectsB\x11\n" +
	"\x0f_max_storage_gbB\x12\n" +
	"\x10_max_sub_tenantsB\f\n" +
	"\n" +
	"_create_byB\f\n" +
	"\n" +
	"_update_byB\x0e\n" +
	"\f_create_timeB\x0e\n" +
	"\f_update_time\"4\n" +
	"\x15GetTenantQuotaRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\rR\btenantId\"\x9d\x02\n" +
	"\x18UpdateTenantQuotaRequest\x124\n" +
	"\x04data\x18\x01 \x01(\v2 .api.user.service.v1.TenantQuotaR\x04data\x12}\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB@\xbaG=: \x12\x1emaxUsers,maxGroups,maxProjects\x92\x02\x18要更新的字段列表R\n" +
	"updateMask\x12<\n" +
	"\voperator_id\x18\x03 \x01(\rB\x16\xbaG\x13\x18\x01\x92\x02\x0e操作用户IDH\x00R\n" +
	"operatorId\x88\x01\x01B\x0e\n" +
	"\f_operator_id\":\n" +
	"\x1bGetTenantPermissionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\rR\btenantId\"a\n" +
	"\x1cGetTenantPermissionsResponse\x12A\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1f.api.user.service.v1.PermissionR\vpermissions\"\xb6\x01\n" +
	"\"BatchAssignTenantPermissionRequest\x12<\n" +
	"\voperator_id\x18\x01 \x01(\rB\x16\xbaG\x13\x18\x01\x92\x02\x0e操作用户IDH\x00R\n" +
	"operatorId\x88\x01\x01\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\rR\btenantId\x12%\n" +
	"\x0epermission_ids\x18\x03 \x03(\rR\rpermissionIdsB\x0e\n" +
	"\f_operator_id\"\xb6\x01\n" +
	"\"BatchRevokeTenantPermissionRequest\x12<\n" +
	"\voperator_id\x18\x01 \x01(\rB\x16\xbaG\x13\x18\x01\x92\x02\x0e操作用户IDH\x00R\n" +
	"operatorId\x88\x01\x01\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\rR\btenantId\x12%\n" +
	"\x0epermission_ids\x18\x03 \x03(\rR\rpermissionIdsB\x0e\n" +
	"\f_operator_id2\xa3\t\n" +
	"\rTenantService\x12_\n" +
	"\n" +
	"ListTenant\x12&.pkg.utils.pagination.v1.PagingRequest\x1a'.api.user.service.v1.ListTenantResponse\"\x00\x12Q\n" +
	"\tGetTenant\x12%.api.user.service.v1.GetTenantRequest\x1a\x1b.api.user.service.v1.Tenant\"\x00\x12R\n" +
	"\fCreateTenant\x12(.api.user.service.v1.CreateTenantRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\fUpdateTenant\x12(.api.user.service.v1.UpdateTenantRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\fDeleteTenant\x12(.api.user.service.v1.DeleteTenantRequest\x1a\x16.google.protobuf.Empty\"\x00\x12e\n" +
	"\rListSubTenant\x12).api.user.service.v1.ListSubTenantRequest\x1a'.api.user.service.v1.ListTenantResponse\"\x00\x12X\n" +
	"\x0fCreateSubTenant\x12+.api.user.service.v1.CreateSubTenantRequest\x1a\x16.google.protobuf.Empty\"\x00\x12`\n" +
	"\x0eGetTenantQuota\x12*.api.user.service.v1.GetTenantQuotaRequest\x1a .api.user.service.v1.TenantQuota\"\x00\x12\\\n" +
	"\x11UpdateTenantQuota\x12-.api.user.service.v1.UpdateTenantQuotaRequest\x1a\x16.google.protobuf.Empty\"\x00\x12}\n" +
	"\x14GetTenantPermissions\x120.api.user.service.v1.GetTenantPermissionsRequest\x1a1.api.user.service.v1.GetTenantPermissionsResponse\"\x00\x12p\n" +
	"\x1bBatchAssignTenantPermission\x127.api.user.service.v1.BatchAssignTenantPermissionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12p\n" +
	"\x1bBatchRevokeTenantPermission\x127.api.user.service.v1.BatchRevokeTenantPermissionRequest\x1a\x16.google.protobuf.Empty\"\x00B;\n" +
	"\x13api.user.service.v1P\x01Z\"om-platform/api/user/service/v1;v1b\x06proto3"

var (
	file_api_user_service_v1_tenant_proto_rawDescOnce sync.Once
	file_api_user_service_v1_tenant_proto_rawDescData []byte
)

func file_api_user_service_v1_tenant_proto_rawDescGZIP() []byte {
	file_api_user_service_v1_tenant_proto_rawDescOnce.Do(func() {
		file_api_user_service_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_service_v1_tenant_proto_rawDesc), len(file_api_user_service_v1_tenant_proto_rawDesc)))
	})
	return file_api_user_service_v1_tenant_proto_rawDescData
}

var file_api_user_service_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_user_service_v1_tenant_proto_goTypes = []any{
	(*Tenant)(nil),                             // 0: api.user.service.v1.Tenant
	(*ListTenantResponse)(nil),                 // 1: api.user.service.v1.ListTenantResponse
	(*GetTenantRequest)(nil),                   // 2: api.user.service.v1.GetTenantRequest
	(*CreateTenantRequest)(nil),                // 3: api.user.service.v1.CreateTenantRequest
	(*UpdateTenantRequest)(nil),                // 4: api.user.service.v1.UpdateTenantRequest
	(*DeleteTenantRequest)(nil),                // 5: api.user.service.v1.DeleteTenantRequest
	(*ListSubTenantRequest)(nil),               // 6: api.user.service.v1.ListSubTenantRequest
	(*CreateSubTenantRequest)(nil),             // 7: api.user.service.v1.CreateSubTenantRequest
	(*TenantQuota)(nil),                        // 8: api.user.service.v1.TenantQuota
	(*GetTenantQuotaRequest)(nil),              // 9: api.user.service.v1.GetTenantQuotaRequest
	(*UpdateTenantQuotaRequest)(nil),           // 10: api.user.service.v1.UpdateTenantQuotaRequest
	(*GetTenantPermissionsRequest)(nil),        // 11: api.user.service.v1.GetTenantPermissionsRequest
	(*GetTenantPermissionsResponse)(nil),       // 12: api.user.service.v1.GetTenantPermissionsResponse
	(*BatchAssignTenantPermissionRequest)(nil), // 13: api.user.service.v1.BatchAssignTenantPermissionRequest
	(*BatchRevokeTenantPermissionRequest)(nil), // 14: api.user.service.v1.BatchRevokeTenantPermissionRequest
	(*timestamppb.Timestamp)(nil),              // 15: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),              // 16: google.protobuf.FieldMask
	(*v1.PagingRequest)(nil),                   // 17: pkg.utils.pagination.v1.PagingRequest
	(*Permission)(nil),                         // 18: api.user.service.v1.Permission
	(*emptypb.Empty)(nil),                      // 19: google.protobuf.Empty
}
var file_api_user_service_v1_tenant_proto_depIdxs = []int32{
	15, // 0: api.user.service.v1.Tenant.subscription_at:type_name -> google.protobuf.Timestamp
	15, // 1: api.user.service.v1.Tenant.unsubscribe_at:type_name -> google.protobuf.Timestamp
	15, // 2: api.user.service.v1.Tenant.create_time:type_name -> google.protobuf.Timestamp
	15, // 3: api.user.service.v1.Tenant.update_time:type_name -> google.protobuf.Timestamp
	15, // 4: api.user.service.v1.Tenant.delete_time:type_name -> google.protobuf.Timestamp
	0,  // 5: api.user.service.v1.ListTenantResponse.items:type_name -> api.user.service.v1.Tenant
	0,  // 6: api.user.service.v1.CreateTenantRequest.data:type_name -> api.user.service.v1.Tenant
	0,  // 7: api.user.service.v1.UpdateTenantRequest.data:type_name -> api.user.service.v1.Tenant
	16, // 8: api.user.service.v1.UpdateTenantRequest.update_mask:type_name -> google.protobuf.FieldMask
	17, // 9: api.user.service.v1.ListSubTenantRequest.paging:type_name -> pkg.utils.pagination.v1.PagingRequest
	0,  // 10: api.user.service.v1.CreateSubTenantRequest.data:type_name -> api.user.service.v1.Tenant
	15, // 11: api.user.service.v1.TenantQuota.create_time:type_name -> google.protobuf.Timestamp
	15, // 12: api.user.service.v1.TenantQuota.update_time:type_name -> google.protobuf.Timestamp
	8,  // 13: api.user.service.v1.UpdateTenantQuotaRequest.data:type_name -> api.user.service.v1.TenantQuota
	16, // 14: api.user.service.v1.UpdateTenantQuotaRequest.update_mask:type_name -> google.protobuf.FieldMask
	18, // 15: api.user.service.v1.GetTenantPermissionsResponse.permissions:type_name -> api.user.service.v1.Permission
	17, // 16: api.user.service.v1.TenantService.ListTenant:input_type -> pkg.utils.pagination.v1.PagingRequest
	2,  // 17: api.user.service.v1.TenantService.GetTenant:input_type -> api.user.service.v1.GetTenantRequest
	3,  // 18: api.user.service.v1.TenantService.CreateTenant:input_type -> api.user.service.v1.CreateTenantRequest
	4,  // 19: api.user.service.v1.TenantService.UpdateTenant:input_type -> api.user.service.v1.UpdateTenantRequest
	5,  // 20: api.user.service.v1.TenantService.DeleteTenant:input_type -> api.user.service.v1.DeleteTenantRequest
	6,  // 21: api.user.service.v1.TenantService.ListSubTenant:input_type -> api.user.service.v1.ListSubTenantRequest
	7,  // 22: api.user.service.v1.TenantService.CreateSubTenant:input_type -> api.user.service.v1.CreateSubTenantRequest
	9,  // 23: api.user.service.v1.TenantService.GetTenantQuota:input_type -> api.user.service.v1.GetTenantQuotaRequest
	10, // 24: api.user.service.v1.TenantService.UpdateTenantQuota:input_type -> api.user.service.v1.UpdateTenantQuotaRequest
	11, // 25: api.user.service.v1.TenantService.GetTenantPermissions:input_type -> api.user.service.v1.GetTenantPermissionsRequest
	13, // 26: api.user.service.v1.TenantService.BatchAssignTenantPermission:input_type -> api.user.service.v1.BatchAssignTenantPermissionRequest
	14, // 27: api.user.service.v1.TenantService.BatchRevokeTenantPermission:input_type -> api.user.service.v1.BatchRevokeTenantPermissionRequest
	1,  // 28: api.user.service.v1.TenantService.ListTenant:output_type -> api.user.service.v1.ListTenantResponse
	0,  // 29: api.user.service.v1.TenantService.GetTenant:output_type -> api.user.service.v1.Tenant
	19, // 30: api.user.service.v1.TenantService.CreateTenant:output_type -> google.protobuf.Empty
	19, // 31: api.user.service.v1.TenantService.UpdateTenant:output_type -> google.protobuf.Empty
	19, // 32: api.user.service.v1.TenantService.DeleteTenant:output_type -> google.protobuf.Empty
	1,  // 33: api.user.service.v1.TenantService.ListSubTenant:output_type -> api.user.service.v1.ListTenantResponse
	19, // 34: api.user.service.v1.TenantService.CreateSubTenant:output_type -> google.protobuf.Empty
	8,  // 35: api.user.service.v1.TenantService.GetTenantQuota:output_type -> api.user.service.v1.TenantQuota
	19, // 36: api.user.service.v1.TenantService.UpdateTenantQuota:output_type -> google.protobuf.Empty
	12, // 37: api.user.service.v1.TenantService.GetTenantPermissions:output_type -> api.user.service.v1.GetTenantPermissionsResponse
	19, // 38: api.user.service.v1.TenantService.BatchAssignTenantPermission:output_type -> google.protobuf.Empty
	19, // 39: api.user.service.v1.TenantService.BatchRevokeTenantPermission:output_type -> google.protobuf.Empty
	28, // [28:40] is the sub-list for method output_type
	16, // [16:28] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_user_service_v1_tenant_proto_init() }
func file_api_user_service_v1_tenant_proto_init() {
	if File_api_user_service_v1_tenant_proto != nil {
		return
	}
	file_api_user_service_v1_permission_proto_init()
	file_api_user_service_v1_tenant_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_user_service_v1_tenant_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_user_service_v1_tenant_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_user_service_v1_tenant_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_user_service_v1_tenant_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_user_service_v1_tenant_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_user_service_v1_tenant_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_user_service_v1_tenant_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_user_service_v1_tenant_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_service_v1_tenant_proto_rawDesc), len(file_api_user_service_v1_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_service_v1_tenant_proto_goTypes,
		DependencyIndexes: file_api_user_service_v1_tenant_proto_depIdxs,
		MessageInfos:      file_api_user_service_v1_tenant_proto_msgTypes,
	}.Build()
	File_api_user_service_v1_tenant_proto = out.File
	file_api_user_service_v1_tenant_proto_goTypes = nil
	file_api_user_service_v1_tenant_proto_depIdxs = nil
}
