// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: api/user/service/v1/tenant.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	v1 "om-platform/pkg/utils/pagination/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantService_ListTenant_FullMethodName                  = "/api.user.service.v1.TenantService/ListTenant"
	TenantService_GetTenant_FullMethodName                   = "/api.user.service.v1.TenantService/GetTenant"
	TenantService_CreateTenant_FullMethodName                = "/api.user.service.v1.TenantService/CreateTenant"
	TenantService_UpdateTenant_FullMethodName                = "/api.user.service.v1.TenantService/UpdateTenant"
	TenantService_DeleteTenant_FullMethodName                = "/api.user.service.v1.TenantService/DeleteTenant"
	TenantService_ListSubTenant_FullMethodName               = "/api.user.service.v1.TenantService/ListSubTenant"
	TenantService_CreateSubTenant_FullMethodName             = "/api.user.service.v1.TenantService/CreateSubTenant"
	TenantService_GetTenantQuota_FullMethodName              = "/api.user.service.v1.TenantService/GetTenantQuota"
	TenantService_UpdateTenantQuota_FullMethodName           = "/api.user.service.v1.TenantService/UpdateTenantQuota"
	TenantService_GetTenantPermissions_FullMethodName        = "/api.user.service.v1.TenantService/GetTenantPermissions"
	TenantService_BatchAssignTenantPermission_FullMethodName = "/api.user.service.v1.TenantService/BatchAssignTenantPermission"
	TenantService_BatchRevokeTenantPermission_FullMethodName = "/api.user.service.v1.TenantService/BatchRevokeTenantPermission"
)

// TenantServiceClient is the client API for TenantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 租户服务
type TenantServiceClient interface {
	// 查询租户列表
	ListTenant(ctx context.Context, in *v1.PagingRequest, opts ...grpc.CallOption) (*ListTenantResponse, error)
	// 查询租户详情
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// 创建租户
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新租户
	UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除租户
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 查询子租户列表
	ListSubTenant(ctx context.Context, in *ListSubTenantRequest, opts ...grpc.CallOption) (*ListTenantResponse, error)
	// 创建子租户
	CreateSubTenant(ctx context.Context, in *CreateSubTenantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 查询租户资源配额
	GetTenantQuota(ctx context.Context, in *GetTenantQuotaRequest, opts ...grpc.CallOption) (*TenantQuota, error)
	// 更新租户资源配额
	UpdateTenantQuota(ctx context.Context, in *UpdateTenantQuotaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取租户权限列表
	GetTenantPermissions(ctx context.Context, in *GetTenantPermissionsRequest, opts ...grpc.CallOption) (*GetTenantPermissionsResponse, error)
	// 批量分配租户权限
	BatchAssignTenantPermission(ctx context.Context, in *BatchAssignTenantPermissionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 批量撤销租户权限
	BatchRevokeTenantPermission(ctx context.Context, in *BatchRevokeTenantPermissionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tenantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantServiceClient(cc grpc.ClientConnInterface) TenantServiceClient {
	return &tenantServiceClient{cc}
}

func (c *tenantServiceClient) ListTenant(ctx context.Context, in *v1.PagingRequest, opts ...grpc.CallOption) (*ListTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantResponse)
	err := c.cc.Invoke(ctx, TenantService_ListTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TenantService_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TenantService_UpdateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TenantService_DeleteTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ListSubTenant(ctx context.Context, in *ListSubTenantRequest, opts ...grpc.CallOption) (*ListTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantResponse)
	err := c.cc.Invoke(ctx, TenantService_ListSubTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) CreateSubTenant(ctx context.Context, in *CreateSubTenantRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TenantService_CreateSubTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantQuota(ctx context.Context, in *GetTenantQuotaRequest, opts ...grpc.CallOption) (*TenantQuota, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantQuota)
	err := c.cc.Invoke(ctx, TenantService_GetTenantQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) UpdateTenantQuota(ctx context.Context, in *UpdateTenantQuotaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TenantService_UpdateTenantQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantPermissions(ctx context.Context, in *GetTenantPermissionsRequest, opts ...grpc.CallOption) (*GetTenantPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantPermissionsResponse)
	err := c.cc.Invoke(ctx, TenantService_GetTenantPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) BatchAssignTenantPermission(ctx context.Context, in *BatchAssignTenantPermissionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TenantService_BatchAssignTenantPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) BatchRevokeTenantPermission(ctx context.Context, in *BatchRevokeTenantPermissionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TenantService_BatchRevokeTenantPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantServiceServer is the server API for TenantService service.
// All implementations must embed UnimplementedTenantServiceServer
// for forward compatibility.
//
// 租户服务
type TenantServiceServer interface {
	// 查询租户列表
	ListTenant(context.Context, *v1.PagingRequest) (*ListTenantResponse, error)
	// 查询租户详情
	GetTenant(context.Context, *GetTenantRequest) (*Tenant, error)
	// 创建租户
	CreateTenant(context.Context, *CreateTenantRequest) (*emptypb.Empty, error)
	// 更新租户
	UpdateTenant(context.Context, *UpdateTenantRequest) (*emptypb.Empty, error)
	// 删除租户
	DeleteTenant(context.Context, *DeleteTenantRequest) (*emptypb.Empty, error)
	// 查询子租户列表
	ListSubTenant(context.Context, *ListSubTenantRequest) (*ListTenantResponse, error)
	// 创建子租户
	CreateSubTenant(context.Context, *CreateSubTenantRequest) (*emptypb.Empty, error)
	// 查询租户资源配额
	GetTenantQuota(context.Context, *GetTenantQuotaRequest) (*TenantQuota, error)
	// 更新租户资源配额
	UpdateTenantQuota(context.Context, *UpdateTenantQuotaRequest) (*emptypb.Empty, error)
	// 获取租户权限列表
	GetTenantPermissions(context.Context, *GetTenantPermissionsRequest) (*GetTenantPermissionsResponse, error)
	// 批量分配租户权限
	BatchAssignTenantPermission(context.Context, *BatchAssignTenantPermissionRequest) (*emptypb.Empty, error)
	// 批量撤销租户权限
	BatchRevokeTenantPermission(context.Context, *BatchRevokeTenantPermissionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedTenantServiceServer()
}

// UnimplementedTenantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantServiceServer struct{}

func (UnimplementedTenantServiceServer) ListTenant(context.Context, *v1.PagingRequest) (*ListTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTenant not implemented")
}
func (UnimplementedTenantServiceServer) GetTenant(context.Context, *GetTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedTenantServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedTenantServiceServer) UpdateTenant(context.Context, *UpdateTenantRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenant not implemented")
}
func (UnimplementedTenantServiceServer) DeleteTenant(context.Context, *DeleteTenantRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedTenantServiceServer) ListSubTenant(context.Context, *ListSubTenantRequest) (*ListTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubTenant not implemented")
}
func (UnimplementedTenantServiceServer) CreateSubTenant(context.Context, *CreateSubTenantRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubTenant not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantQuota(context.Context, *GetTenantQuotaRequest) (*TenantQuota, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantQuota not implemented")
}
func (UnimplementedTenantServiceServer) UpdateTenantQuota(context.Context, *UpdateTenantQuotaRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenantQuota not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantPermissions(context.Context, *GetTenantPermissionsRequest) (*GetTenantPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantPermissions not implemented")
}
func (UnimplementedTenantServiceServer) BatchAssignTenantPermission(context.Context, *BatchAssignTenantPermissionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchAssignTenantPermission not implemented")
}
func (UnimplementedTenantServiceServer) BatchRevokeTenantPermission(context.Context, *BatchRevokeTenantPermissionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchRevokeTenantPermission not implemented")
}
func (UnimplementedTenantServiceServer) mustEmbedUnimplementedTenantServiceServer() {}
func (UnimplementedTenantServiceServer) testEmbeddedByValue()                       {}

// UnsafeTenantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantServiceServer will
// result in compilation errors.
type UnsafeTenantServiceServer interface {
	mustEmbedUnimplementedTenantServiceServer()
}

func RegisterTenantServiceServer(s grpc.ServiceRegistrar, srv TenantServiceServer) {
	// If the following call pancis, it indicates UnimplementedTenantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantService_ServiceDesc, srv)
}

func _TenantService_ListTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ListTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ListTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ListTenant(ctx, req.(*v1.PagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_UpdateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).UpdateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_UpdateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).UpdateTenant(ctx, req.(*UpdateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).DeleteTenant(ctx, req.(*DeleteTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_ListSubTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ListSubTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ListSubTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ListSubTenant(ctx, req.(*ListSubTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_CreateSubTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CreateSubTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_CreateSubTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CreateSubTenant(ctx, req.(*CreateSubTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantQuota(ctx, req.(*GetTenantQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_UpdateTenantQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).UpdateTenantQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_UpdateTenantQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).UpdateTenantQuota(ctx, req.(*UpdateTenantQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantPermissions(ctx, req.(*GetTenantPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_BatchAssignTenantPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchAssignTenantPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).BatchAssignTenantPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_BatchAssignTenantPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).BatchAssignTenantPermission(ctx, req.(*BatchAssignTenantPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_BatchRevokeTenantPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRevokeTenantPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).BatchRevokeTenantPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_BatchRevokeTenantPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).BatchRevokeTenantPermission(ctx, req.(*BatchRevokeTenantPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantService_ServiceDesc is the grpc.ServiceDesc for TenantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.service.v1.TenantService",
	HandlerType: (*TenantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTenant",
			Handler:    _TenantService_ListTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _TenantService_GetTenant_Handler,
		},
		{
			MethodName: "CreateTenant",
			Handler:    _TenantService_CreateTenant_Handler,
		},
		{
			MethodName: "UpdateTenant",
			Handler:    _TenantService_UpdateTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _TenantService_DeleteTenant_Handler,
		},
		{
			MethodName: "ListSubTenant",
			Handler:    _TenantService_ListSubTenant_Handler,
		},
		{
			MethodName: "CreateSubTenant",
			Handler:    _TenantService_CreateSubTenant_Handler,
		},
		{
			MethodName: "GetTenantQuota",
			Handler:    _TenantService_GetTenantQuota_Handler,
		},
		{
			MethodName: "UpdateTenantQuota",
			Handler:    _TenantService_UpdateTenantQuota_Handler,
		},
		{
			MethodName: "GetTenantPermissions",
			Handler:    _TenantService_GetTenantPermissions_Handler,
		},
		{
			MethodName: "BatchAssignTenantPermission",
			Handler:    _TenantService_BatchAssignTenantPermission_Handler,
		},
		{
			MethodName: "BatchRevokeTenantPermission",
			Handler:    _TenantService_BatchRevokeTenantPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/service/v1/tenant.proto",
}
